[PHP]
; Отображение ошибок
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Лимиты
memory_limit = 256M
max_execution_time = 60
upload_max_filesize = 64M
post_max_size = 64M

; Временная зона
date.timezone = Europe/Moscow

; Opcache (полезно даже на dev)
[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 0  ; сразу видим изменения файлов